export const ADICIONA_PROJETO = 'ADICIONA_PROJETO';
export const DEFINIR_PROJETO = 'DEFINIR_PROJETO';
export const ALTERA_PROJETO = 'ALTERA_PROJETO';
export const EXCLUI_PROJETO = 'EXCLUI_PROJETO';
export const NOTIFICAR = 'NOTIFICAR';

export const DEFINIR_TAREFAS = 'DEFINIR_TAREFAS';
export const ADICIONA_TAREFA = 'ADICIONA_TAREFA';
export const ALTERA_TAREFA = 'ALTERA_TAREFA';
export const EXCLUI_TAREFA = 'EXCLUI_TAREFA';